const data = [
  {
    name: "Bob Doe",
    age: 35,
    gender: "male",
    about: "I like doing sports and meeting new people",
    lookingFor: "a funny, clever and interesting girl",
    location: "Boston MA",
    image: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    name: "Liza Kortniuk",
    age: 25,
    gender: "female",
    about: "I admire animals and reading books",
    lookingFor: "a solid and responsible man",
    location: "Ukraine, Kharkiv",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "Linda Smith",
    age: 29,
    gender: "female",
    about:
      "disco parties, hanging out with my friends and looking through fashion magazines",
    lookingFor: "a rich, strong and sociable guy",
    location: "Russia, Moscow",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    name: "Mark Johnson",
    age: 50,
    gender: "male",
    about: "riding a motorbike, speed and unusual kinds of sports",
    lookingFor: "a nice, talkative and careful woman",
    location: "Poland, Warsaw",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    name: "Viktoria Halushchak",
    age: 22,
    gender: "female",
    about: "entertainments, catchy films and eating ice cream",
    lookingFor: "not arrogant or bossy boys. Others are ok)",
    location: "Ukraine, Lviv",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    name: "Den Brown",
    age: 39,
    gender: "male",
    about: "I'm a big computer gamer and passion about mountain biking",
    lookingFor: "always a cheerful and cute girl",
    location: "Germany, Berlin",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
];
